# gradle.properties
# org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx2560m -XX:+UseParallelGC -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34

org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true

# KSP optimizations
#org.gradle.java.home=C\:/Program Files/Java/jdk-21
ksp.incremental=true

# Fix for AGP 8.7+ "Several environment variables" error
systemProp.ANDROID_PREFS_ROOT=
systemProp.ANDROID_USER_HOME=C:\\Users\\msi\\.android
org.gradle.project.ANDROID_PREFS_ROOT=
